# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '4week_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 4week_practice
pod 'lottie-ios'
end
